# Generated by Django 5.1.3 on 2024-11-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_profile_review_provider_alter_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='approval',
            field=models.CharField(choices=[('pending approval', 'Pending Approval'), ('approved', 'Approved'), ('not approved', 'Not Approved')], default='pending approval', max_length=16),
        ),
    ]
