# Generated by Django 5.1.2 on 2024-11-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_provider'),
        ('app', '0004_alter_service_image'),
    ]

    operations = [
    ]
