# Generated by Django 5.1.3 on 2024-11-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_merge_0003_profile_provider_0004_alter_service_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
