# Generated by Django 5.1.2 on 2024-11-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_0003_profile_provider_0004_alter_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='provider',
            new_name='isProvider',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
