# Generated by Django 5.1.3 on 2024-11-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_service_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.CharField(
                choices=[
                    ("pending approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("not approved", "Not Approved"),
                ],
                max_length=16,
            ),
        ),
    ]
