# Generated by Django 5.1.2 on 2024-11-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_provider_profile_isprovider_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='isProvider',
            new_name='is_provider',
        ),
    ]
