# Generated by Django 5.1.3 on 2024-11-08 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_profile_review_provider_alter_review_reviewer"),
        ("app", "0007_alter_service_is_active"),
    ]

    operations = []
