# Generated by Django 5.1.3 on 2024-11-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_merge_20241108_1436"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="provider",
        ),
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.CharField(
                choices=[
                    ("Pending Approval", "Pending Approval"),
                    ("Approved", "Approved"),
                    ("Not Approved", "Not Approved"),
                ],
                max_length=16,
            ),
        ),
    ]
