# Generated by Django 5.1.3 on 2024-11-07 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_provider_avatar_provider_location_provider_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='location',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
