# Generated by Django 5.1.2 on 2024-11-06 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_about_profile_contact_email_profile_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
