# Generated by Django 5.1.3 on 2024-11-08 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_service_approval"),
        ("app", "0009_remove_profile_provider_alter_service_is_active"),
    ]

    operations = []
