# Generated by Django 5.1.3 on 2024-11-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_merge_20241108_1726"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
