# Generated by Django 5.1.3 on 2024-11-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_service_is_active'),
        ('app', '0011_alter_service_is_active_chat_message'),
    ]

    operations = [
    ]
