# Generated by Django 5.1.3 on 2024-11-09 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_alter_review_options_alter_review_comment_and_more"),
        ("app", "0012_merge_20241108_2107"),
    ]

    operations = []
