# Generated by Django 5.1.3 on 2024-11-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="approved_by_provider",
            field=models.BooleanField(default=False),
        ),
    ]
