# Generated by Django 5.1.3 on 2024-11-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_message_timestamp'),
        ('app', '0017_rename_date_booking_scheduled_time_and_more'),
    ]

    operations = [
    ]
