# Generated by Django 5.1.3 on 2024-11-09 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_merge_20241109_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='client',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='service',
        ),
        migrations.AddField(
            model_name='chat',
            name='booking',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='app.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
