# Generated by Django 5.1.3 on 2024-11-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_booking_status_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Enter the CSS class or icon name (e.g., 'fas fa-paint-brush')", max_length=50, null=True),
        ),
    ]
