# Generated by Django 5.1.3 on 2024-11-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=80),
        ),
    ]
